### PR TITLE
pagination fixes

### PR DESCRIPTION
**Pull request by gsiegman**
PLEASE NOTE: This version includes a breaking change. Please do not pull into other services until their settings are able to be updated to reflect naming change.

### CODE REVIEW

**Comment by TimGraf** [comment]
Push those beautiful page size parameters!

**Comment by TimGraf** [comment]
LGTM

**Comment by AlexMaskovyak** [comment]
Theoretically shouldn't breaking changes involve a major version alteration?

**Comment by gsiegman** [comment]
Theoretically yes, but we haven't reached 1.0 state yet :smile:

**Comment by AlexMaskovyak** [comment]
Fine. I suppose that's good.

**Pull request merged**
